### ISSUE TITLE
Version parameter on install job does nothing

### ISSUE THREAD

**Issue by mattvanstone** [CircleCI-Public/circleci-cli-orb#13]
### Orb version

0.1.9 and older

### What happened
Specify an explicit version to install in the install job
```yaml
  - circleci-cli/install:
      version: v0.1.15224
```
The job outputs that you want to install version v0.1.15224, but doesn't actually reference it in the install command. It just installs the latest
```
Selected version of CircleCI CLI is v0.1.15224
A different version of the CircleCI CLI is installed (Build Agent version: 1.0.72666-eaa68b41
Built: 2021-06-14T14:18:26+0000); updating it
Starting installation.
Installing CircleCI CLI v0.1.15338
Installing to /usr/local/bin
/usr/local/bin/circleci
CircleCI CLI version 0.1.15338+850f9ac (release) has been installed to /usr/local/bin/circleci
```

### Expected behavior

When you specify a version for the install job, it should install that version.

**Comment by yangchoo** [comment]
Please fix this issue.

This would provide a workaround to any breaking issues with the circleci-cli (e.g. https://github.com/CircleCI-Public/circleci-cli/issues/941).

There are orbs which are currently breaking which depends on this fix such as the continuation orb.

**Comment by yangchoo** [comment]
@brivu Tagging you on the issue for visibility. The upstream bug has been resolved, but it'll be nice to get this in so that we'll have a workaround next time.

Thank you
