### ISSUE TITLE
Remove reliance on the GitHub API

### ISSUE THREAD

**Issue by felicianotech** [CircleCI-Public/circleci-cli-orb#6]
The install command relies on the GitHub API in order to do it's thing. This is starting to cause of issues with rate limiting since we're unauthenticated.

This orb is occasionally having the same issue as the jq orb: https://github.com/CircleCI-Public/jq-orb/issues/10

**Comment by UrielLibbbb** [comment]
Use

**Comment by UrielLibbbb** [comment]
https://github.com/CircleCI-Public/circleci-cli-orb/issues/25
